name = "resettle-development-app-web"
main = "./app/entry.cloudflare.ts"
workers_dev = true
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"

[assets]
directory = "./public/"
binding = "ASSETS"
