name: resettle-dev

networks:
  resettle:

volumes:
  psql:

services:
  psql:
    image: postgres:16
    environment:
      POSTGRES_USER: resettler
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resettle
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - resettle

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - resettle
