name = "resettle-production-service-app"
main = "./src/index.ts"
minify = true
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "8bf6b16566be4f9f88ffe551be3b2531"

[placement]
mode = "smart"

[observability]
enabled = true

[limits]
cpu_ms = 5000
