name = "resettle-development-service-app"
main = "./src/index.ts"
workers_dev = true
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = ""

[placement]
mode = "smart"

[observability]
enabled = true
