import type { CountryAlpha2Code } from '@resettle/schema'

export const ALPHA_2_COUNTRY_NAME_PAIRS: Record<CountryAlpha2Code, string[]> = {
  AD: ['Andorra', 'Principality of Andorra'],
  AE: ['United Arab Emirates', 'United Arab Emirates (UAE)'],
  AF: ['Afghanistan', 'Islamic Republic of Afghanistan'],
  AG: ['Antigua and Barbuda', 'Antigua And Barbuda'],
  AI: ['Anguilla'],
  AL: ['Albania', 'Republic of Albania'],
  AM: ['Armenia', 'Republic of Armenia'],
  AO: ['Angola', 'Republic of Angola'],
  AQ: ['Antarctica'],
  AR: ['Argentina', 'Argentine Republic'],
  AS: ['American Samoa'],
  AT: ['Austria', 'Republic of Austria'],
  AU: ['Australia', 'Commonwealth of Australia'],
  AW: ['Aruba'],
  AX: ['Aland Islands', 'Åland Islands'],
  AZ: ['Azerbaijan', 'Republic of Azerbaijan'],
  BA: [
    'Bosnia and Herzegovina',
    'Bosnia And Herzegovina',
    'Bosnia Herzegovina',
  ],
  BB: ['Barbados'],
  BD: ['Bangladesh'],
  BE: ['Belgium', 'Kingdom of Belgium'],
  BF: ['Burkina Faso'],
  BG: ['Bulgaria', 'Republic of Bulgaria'],
  BH: ['Bahrain', 'Kingdom of Bahrain'],
  BI: ['Burundi', 'Republic of Burundi'],
  BJ: ['Benin', 'Republic of Benin'],
  BL: ['Saint Barthelemy'],
  BM: ['Bermuda'],
  BN: ['Brunei', 'Brunei Darussalam'],
  BO: [
    'Bolivia',
    'Plurinational State of Bolivia',
    'Bolivia (Plurinational State of)',
  ],
  BQ: [
    'Bonaire',
    'Bonaire, Saint Eustatius and Saba',
    'Caribbean Netherlands',
    'Netherlands Antilles',
  ],
  BR: ['Brazil', 'Federative Republic of Brazil'],
  BS: ['Bahamas', 'Commonwealth of The Bahamas'],
  BT: ['Bhutan', 'Kingdom of Bhutan'],
  BV: ['Bouvet Island'],
  BW: ['Botswana', 'Republic of Botswana'],
  BY: ['Belarus', 'Republic of Belarus'],
  BZ: ['Belize'],
  CA: ['Canada'],
  CC: ['Cocos Islands', 'Territory of Cocos (Keeling) Islands'],
  CD: [
    'D.R. Congo',
    'Democratic Republic of the Congo',
    'Congo, Democratic Republic of the',
    'DR Congo',
    'Democratic Republic of Congo',
  ],
  CF: ['Central African Republic', 'Central African Republic (CAR)'],
  CG: ['Congo', 'Republic of the Congo'],
  CH: ['Switzerland'],
  CI: [
    "Cote d'Ivoire",
    'Republic of Côte d’Ivoire',
    'Côte d’Ivoire',
    'Ivory Coast',
    "Côte d'Ivoire",
    "Côte d'Ivoire",
    'Cote D Ivoire',
  ],
  CK: ['Cook Islands'],
  CL: ['Chile', 'Republic of Chile'],
  CM: ['Cameroon', 'Republic of Cameroon'],
  CN: ['China', 'People’s Republic of China', "People's Republic of China"],
  CO: ['Colombia', 'Republic of Colombia'],
  CR: ['Costa Rica', 'Republic of Costa Rica'],
  CU: ['Cuba', 'Republic of Cuba'],
  CV: ['Cape Verde', 'Republic of Cabo Verde', 'Cabo Verde'],
  CW: ['Curacao', 'Country of Curaçao', 'Curaçao', 'Curaçao'],
  CX: ['Christmas Island', 'Territory of Christmas Island'],
  CY: ['Cyprus', 'Republic of Cyprus', 'Northern Cyprus'],
  CZ: ['Czechia', 'Czech Republic'],
  DE: ['Germany', 'Federal Republic of Germany'],
  DJ: ['Djibouti', 'Republic of Djibouti'],
  DK: ['Denmark', 'Kingdom of Denmark'],
  DM: ['Dominica'],
  DO: ['Dominican Republic'],
  DZ: ['Algeria', "People's Democratic Republic of Algeria"],
  EC: ['Ecuador', 'Republic of Ecuador'],
  EE: ['Estonia', 'Republic of Estonia'],
  EG: ['Egypt', 'Arab Republic of Egypt'],
  EH: ['Western Sahara'],
  ER: ['Eritrea', 'State of Eritrea'],
  ES: ['Spain', 'Kingdom of Spain'],
  ET: ['Ethiopia', 'Federal Democratic Republic of Ethiopia'],
  FI: ['Finland', 'Republic of Finland'],
  FJ: ['Fiji', 'Viti'],
  FK: ['Falkland Islands', 'Falkland Islands, Malvinas'],
  FM: [
    'Micronesia',
    'Federated States of Micronesia',
    'Micronesia (Fed. States of)',
    'Micronesia (Federated States of)',
  ],
  FO: ['Faroe Islands'],
  FR: ['France', 'Republic of France'],
  GA: ['Gabon', 'Gabonese Republic'],
  GB: [
    'United Kingdom',
    'United Kingdom of Great Britain and Northern Ireland',
    'United Kingdom (UK)',
  ],
  GD: ['Grenada'],
  GE: ['Georgia'],
  GF: ['French Guiana', 'Guyane'],
  GG: ['Guernsey', 'Bailiwick of Guernsey', 'Alderney'],
  GH: ['Ghana', 'Republic of Ghana'],
  GI: ['Gibraltar'],
  GL: ['Greenland'],
  GM: ['Gambia'],
  GN: ['Guinea', 'Republic of Guinea'],
  GP: ['Guadeloupe'],
  GQ: ['Equatorial Guinea', 'Republic of Equatorial Guinea'],
  GR: ['Greece', 'Hellenic Republic'],
  GS: ['South Georgia', 'South Georgia and the South Sandwich Islands'],
  GT: ['Guatemala', 'Republic of Guatemala'],
  GU: ['Guam'],
  GW: ['Guinea-Bissau', 'Republic of Guinea-Bissau'],
  GY: ['Guyana', 'Co-operative Republic of Guyana'],
  HK: [
    'Hong Kong',
    'Hong Kong Special Administrative Region',
    'Hong Kong (China)',
    'Hong Kong, China',
  ],
  HM: [
    'Heard Island and McDonald Islands',
    'Territory of Heard Island and McDonald Islands',
  ],
  HN: ['Honduras', 'Republic of Honduras'],
  HR: ['Croatia', 'Republic of Croatia'],
  HT: ['Haiti', 'Republic of Haiti'],
  HU: ['Hungary'],
  ID: ['Indonesia', 'Republic of Indonesia'],
  IE: ['Ireland'],
  IL: ['Israel', 'State of Israel'],
  IM: ['Isle of Man', 'Isle Of Man'],
  IN: ['India', 'Republic of India'],
  IO: ['British Indian Ocean Territory', 'BIOT'],
  IQ: ['Iraq', 'Republic of Iraq'],
  IR: ['Iran', 'Islamic Republic of Iran', 'Iran (Islamic Republic of)'],
  IS: ['Iceland'],
  IT: ['Italy', 'Italian Republic'],
  JE: ['Jersey', 'Bailiwick of Jersey'],
  JM: ['Jamaica'],
  JO: ['Jordan', 'Hashemite Kingdom of Jordan'],
  JP: ['Japan'],
  KE: ['Kenya', 'Republic of Kenya'],
  KG: ['Kyrgyzstan', 'Kyrgyz Republic'],
  KH: ['Cambodia', 'Kingdom of Cambodia'],
  KI: ['Kiribati', 'Republic of Kiribati'],
  KM: ['Comoros', 'Union of the Comoros'],
  KN: [
    'Saint Kitts and Nevis',
    'Federation of Saint Kitts and Nevis',
    'Saint Kitts And Nevis',
    'St Kitts and Nevis',
  ],
  KP: [
    'North Korea',
    'Democratic People’s Republic of Korea',
    "Dem. People's Republic of Korea",
  ],
  KR: ['South Korea', 'Republic of Korea'],
  KW: ['Kuwait', 'State of Kuwait'],
  KY: ['Cayman Islands'],
  KZ: ['Kazakhstan', 'Republic of Kazakhstan'],
  LA: [
    'Laos',
    'Lao People’s Democratic Republic',
    "Lao People's Democratic Republic",
  ],
  LB: ['Lebanon'],
  LC: ['Saint Lucia', 'St Lucia'],
  LI: ['Liechtenstein', 'Principality of Liechtenstein'],
  LK: ['Sri Lanka', 'Democratic Socialist Republic of Sri Lanka'],
  LR: ['Liberia', 'Republic of Liberia'],
  LS: ['Lesotho', 'Kingdom of Lesotho'],
  LT: ['Lithuania', 'Republic of Lithuania'],
  LU: ['Luxembourg', 'Grand Duchy of Luxembourg'],
  LV: ['Latvia', 'Republic of Latvia'],
  LY: ['Libya'],
  MA: ['Morocco', 'Kingdom of Morocco'],
  MC: ['Monaco', 'Principality of Monaco'],
  MD: ['Moldova', 'Republic of Moldova'],
  ME: ['Montenegro'],
  MF: ['Saint-Martin'],
  MG: ['Madagascar', 'Republic of Madagascar'],
  MH: ['Marshall Islands', 'Republic of the Marshall Islands'],
  MK: ['North Macedonia', 'Macedonia', 'TFYR Macedonia'],
  ML: ['Mali', 'Republic of Mali'],
  MM: [
    'Myanmar',
    'Union of Burma',
    'Myanmar (Burma)',
    'Republic of the Union of Myanmar',
  ],
  MN: ['Mongolia'],
  MO: [
    'Macao',
    'Macau Special Administrative Region',
    'Macau',
    'Macao (China)',
    'Macao, China',
  ],
  MP: [
    'Northern Mariana Islands',
    'Commonwealth of the Northern Mariana Islands',
  ],
  MQ: ['Martinique'],
  MR: ['Mauritania', 'Islamic Republic of Mauritania'],
  MS: ['Montserrat'],
  MT: ['Malta', 'Republic of Malta'],
  MU: ['Mauritius', 'Republic of Mauritius'],
  MV: ['Maldives', 'the Maldives', 'Republic of Maldives'],
  MW: ['Malawi', 'Republic of Malawi'],
  MX: ['Mexico'],
  MY: ['Malaysia'],
  MZ: ['Mozambique', 'Republic of Mozambique'],
  NA: ['Namibia', 'Republic of Namibia'],
  NC: ['New Caledonia'],
  NE: ['Niger', 'Republic of Niger'],
  NF: ['Norfolk Island', 'Territory of Norfolk Island'],
  NG: ['Nigeria', 'Federal Republic of Nigeria'],
  NI: ['Nicaragua', 'Republic of Nicaragua'],
  NL: ['Netherlands', 'Kingdom of the Netherlands'],
  NO: ['Norway', 'Kingdom of Norway'],
  NP: ['Nepal'],
  NR: ['Nauru'],
  NU: ['Niue'],
  NZ: ['New Zealand'],
  OM: ['Oman', 'Sultanate of Oman'],
  PA: ['Panama', 'Republic of Panama'],
  PE: ['Peru', 'Republic of Peru'],
  PF: ['French Polynesia'],
  PG: ['Papua New Guinea', 'Independent State of Papua New Guinea'],
  PH: ['Philippines', 'Republic of the Philippines'],
  PK: ['Pakistan', 'Islamic Republic of Pakistan'],
  PL: ['Poland', 'Republic of Poland'],
  PM: ['Saint Pierre and Miquelon', 'Saint-Pierre And Miquelon'],
  PN: ['Pitcairn Islands', 'Pitcairn, Henderson, Ducie and Oeno Islands'],
  PR: ['Puerto Rico'],
  PS: [
    'Palestine',
    'State of Palestine',
    'Occupied Palestinian Territory',
    'Palestinian Territories',
  ],
  PT: ['Portugal', 'Portuguese Republic'],
  PW: ['Palau', 'Republic of Palau'],
  PY: ['Paraguay', 'Republic of Paraguay'],
  QA: ['Qatar', 'State of Qatar'],
  RE: ['Reunion', 'Réunion', 'Réunion'],
  RO: ['Romania'],
  RS: ['Serbia'],
  RU: ['Russia', 'Russian Federation', 'Russia (Russian Federation)'],
  RW: ['Rwanda', 'Republic of Rwanda'],
  SA: ['Saudi Arabia', 'Kingdom of Saudi Arabia'],
  SB: ['Solomon Islands'],
  SC: ['Seychelles', 'Republic of Seychelles'],
  SD: ['Sudan', 'Republic of the Sudan'],
  SE: ['Sweden', 'Kingdom of Sweden'],
  SG: ['Singapore', 'Republic of Singapore'],
  SH: ['Saint Helena', 'Saint Helena, Ascension, and Tristan da Cunha'],
  SI: ['Slovenia', 'Republic of Slovenia'],
  SJ: ['Svalbard and Jan Mayen'],
  SK: ['Slovakia', 'Slovak Republic'],
  SL: ['Sierra Leone', 'Republic of Sierra Leone'],
  SM: ['San Marino', 'Repubblica di San Marino'],
  SN: ['Senegal', 'Republic of Senegal'],
  SO: ['Somalia'],
  SR: ['Suriname', 'Republic of Suriname'],
  SS: ['South Sudan'],
  ST: [
    'Sao Tome and Principe',
    'Sao Tome And Principe',
    'São Tomé and Príncipe',
  ],
  SV: ['El Salvador', 'Republic of El Salvador'],
  SX: ['Sint Maarten'],
  SY: ['Syria', 'Syrian Arab Republic'],
  SZ: ['Eswatini', 'Swaziland'],
  TC: [
    'Turks and Caicos Islands',
    'Turks And Caicos Islands',
    'Turks and Caicos',
  ],
  TD: ['Chad', 'Republic of Chad'],
  TF: ['French Southern Territories', 'French Southern and Antarctic Lands'],
  TG: ['Togo', 'Togolese Republic'],
  TH: ['Thailand', 'Kingdom of Thailand'],
  TJ: ['Tajikistan', 'Republic of Tajikistan'],
  TK: ['Tokelau'],
  TL: [
    'Timor Leste',
    'Democratic Republic of Timor-Leste',
    'Timor-Leste',
    'Timor',
  ],
  TM: ['Turkmenistan'],
  TN: ['Tunisia', 'Republic of Tunisia'],
  TO: ['Tonga', 'Kingdom of Tonga'],
  TR: ['Turkey', 'Republic of Turkey', 'Türkiye'],
  TT: [
    'Trinidad and Tobago',
    'Republic of Trinidad and Tobago',
    'Trinidad And Tobago',
  ],
  TV: ['Tuvalu'],
  TW: ['Taiwan', 'Taiwan, China'],
  TZ: [
    'Tanzania',
    'United Republic of Tanzania',
    'Tanzania, United Republic of',
  ],
  UA: ['Ukraine'],
  UG: ['Uganda', 'Republic of Uganda'],
  UM: ['United States Minor Outlying Islands'],
  US: [
    'United States',
    'United States of America',
    'United States of America (USA)',
  ],
  UY: ['Uruguay', 'Oriental Republic of Uruguay'],
  UZ: ['Uzbekistan', 'Republic of Uzbekistan'],
  VA: [
    'Vatican',
    'State of the Vatican City',
    'Vatican City (Holy See)',
    'Vatican City',
  ],
  VC: [
    'Saint Vincent',
    'Saint Vincent and the Grenadines',
    'Saint Vincent And The Grenadines',
    'St Vincent and the Grenadines',
  ],
  VE: [
    'Venezuela',
    'Bolivarian Republic of Venezuela',
    'Venezuela (Bolivarian Republic of)',
  ],
  VG: ['British Virgin Islands'],
  VI: [
    'United States Virgin Islands',
    'U.S. Virgin Islands',
    'Us Virgin Islands',
    'US Virgin Islands',
  ],
  VN: ['Vietnam', 'Socialist Republic of Vietnam', 'Viet Nam'],
  VU: ['Vanuatu', 'Republic of Vanuatu'],
  WF: ['Wallis and Futuna', 'Wallis et Futuna', 'Wallis And Futuna'],
  WS: ['Samoa', 'Independent State of Samoa'],
  XK: ['Kosovo', 'Republic of Kosovo', 'Kosovo (Disputed Territory)'],
  YE: ['Yemen', 'Republic of Yemen'],
  YT: ['Mayotte'],
  ZA: ['South Africa'],
  ZM: ['Zambia', 'Republic of Zambia'],
  ZW: ['Zimbabwe', 'Republic of Zimbabwe'],
}

export const convertAlpha2ToCountyNames = (
  from: CountryAlpha2Code,
): string[] => {
  return ALPHA_2_COUNTRY_NAME_PAIRS[from]
}

export const convertCountryNameToAlpha2 = (
  from: string,
  ignoreCase = false,
): CountryAlpha2Code | null => {
  for (const [key, value] of Object.entries(ALPHA_2_COUNTRY_NAME_PAIRS)) {
    const convertedValue = ignoreCase ? value.map(v => v.toLowerCase()) : value
    const convertedFrom = ignoreCase ? from.toLowerCase() : from
    if (convertedValue.includes(convertedFrom)) {
      return key as CountryAlpha2Code
    }
  }

  return null
}

export const getStandardCountryName = (code: CountryAlpha2Code) => {
  return convertAlpha2ToCountyNames(code)[0]
}
